name: shared-lib
version: '0.1.0.0'
synopsis: Shared library
description: Shared library
category: Web
author: Todd Mohney
maintainer: toddmohney@gmail.com
copyright: 2017 Todd Mohney
license: MIT
github: toddmohney/servant-template

extra-source-files:
- README.md

default-extensions:
- DeriveGeneric
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- OverloadedStrings
- Rank2Types
- RecordWildCards

ghc-options:
- -Wall
- -Werror
- -fno-warn-warnings-deprecations
- -freverse-errors
- -fwarn-unused-binds
- -fwarn-unused-imports
- -fwarn-unused-matches

dependencies:
- base >=4.7 && <5
- bytestring
- monad-logger
- mtl
- text
- time

library:
  source-dirs: src
  exposed-modules:
  - CoinCoinCoin.Class
  - CoinCoinCoin.Database.Config
  - CoinCoinCoin.Environment
  - CoinCoinCoin.Errors
  - CoinCoinCoin.Logging
  - CoinCoinCoin.MessageQueue
  - CoinCoinCoin.Time
  dependencies:
  - aeson
  - async
  - exceptions
  - hstatsd
  - lens
  - lens-aeson
  - milena
  - network
  - persistent
  - persistent-postgresql
  - uuid
  - vector

tests:
  shared-lib-test:
    main: Spec.hs
    source-dirs:
    - test
    ghc-options:
    - -fno-warn-orphans
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson
    - file-embed
    - hspec
    - shared-lib
